"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowRight, Check, KeyRound, ShieldCheck } from "lucide-react";

export default function AdminAccess({ forcePasswordChange: initialForce, mfaEnrolled: initialMfa, email }: { forcePasswordChange: boolean; mfaEnrolled: boolean; email: string }) {
  const [forcePasswordChange, setForcePasswordChange] = useState(initialForce);
  const [mfaEnrolled, setMfaEnrolled] = useState(initialMfa);
  const [secret, setSecret] = useState("");
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  useEffect(() => { if (!forcePasswordChange && !mfaEnrolled) fetch("/api/admin/access", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "setup" }) }).then(r => r.json()).then(result => setSecret(result.secret ?? "")); }, [forcePasswordChange, mfaEnrolled]);
  async function changePassword(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const form = new FormData(event.currentTarget); if (form.get("newPassword") !== form.get("confirm")) { setError("New passwords do not match."); setBusy(false); return; } const response = await fetch("/api/auth/password/change", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ currentPassword: form.get("currentPassword"), newPassword: form.get("newPassword") }) }); const result = await response.json(); if (!response.ok) { setError(result.error); setBusy(false); return; } setForcePasswordChange(false); setBusy(false); }
  async function verify(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const code = new FormData(event.currentTarget).get("code"); const response = await fetch("/api/admin/access", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "verify", code }) }); const result = await response.json(); if (!response.ok) { setError(result.error); setBusy(false); return; } setMfaEnrolled(true); window.location.href = "/admin"; }
  return <main className="admin-access-page"><Link className="admin-access-logo" href="/"><span>n2</span><strong>nice 2 network</strong><i>ADMIN</i></Link><section className="admin-access-card">{forcePasswordChange ? <><span className="access-icon"><KeyRound size={22}/></span><span className="eyebrow">SECURE YOUR ACCOUNT</span><h1>Replace your temporary password.</h1><p>This password was used only to provision the master account. Choose a private password before enabling administrator access.</p><form onSubmit={changePassword}><label>Temporary password<input name="currentPassword" type="password" autoComplete="current-password" required/></label><label>New password<input name="newPassword" type="password" autoComplete="new-password" minLength={10} required/></label><label>Confirm new password<input name="confirm" type="password" autoComplete="new-password" minLength={10} required/></label>{error&&<p className="form-error">{error}</p>}<button className="primary-button wide" disabled={busy}>{busy?"Updating…":<>Update password <ArrowRight size={16}/></>}</button></form></> : <><span className="access-icon"><ShieldCheck size={22}/></span><span className="eyebrow">ADMIN VERIFICATION</span><h1>{mfaEnrolled?"Confirm it’s you.":"Add an authenticator."}</h1><p>{mfaEnrolled?"Enter the current six-digit code from your authenticator app.":`Add ${email} to an authenticator app using this setup key.`}</p>{!mfaEnrolled&&<div className="mfa-secret"><small>SETUP KEY</small><strong>{secret||"Preparing secure key…"}</strong><button onClick={()=>navigator.clipboard.writeText(secret)} disabled={!secret}>Copy</button></div>}<form onSubmit={verify}><label>Six-digit code<input name="code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required/></label>{error&&<p className="form-error">{error}</p>}<button className="primary-button wide" disabled={busy||(!mfaEnrolled&&!secret)}>{busy?"Verifying…":<>{mfaEnrolled?"Enter admin":"Enable and continue"} <Check size={16}/></>}</button></form></>}</section></main>;
}
