"use client";
/* eslint-disable @next/next/no-img-element */

import { FormEvent, useState } from "react";
import Link from "next/link";
import { ArrowRight, Check, MapPin, UsersRound } from "lucide-react";

type NetworkMember={id:string;name:string|null;image:string|null;profession:string|null;location:string|null;sharedSkills:string[];sharedInterests:string[];score:number};

export default function OnboardingPage(){
  const [step,setStep]=useState<"profile"|"network">("profile");
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState("");
  const [network,setNetwork]=useState<NetworkMember[]>([]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const data=new FormData(event.currentTarget);const split=(name:string)=>String(data.get(name)).split(",").map(value=>value.trim()).filter(Boolean);const response=await fetch("/api/auth/onboarding",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({profession:data.get("profession"),primarySkill:data.get("primarySkill"),secondarySkill:data.get("secondarySkill"),tertiarySkill:data.get("tertiarySkill"),interests:split("interests"),location:data.get("location")})});const result=await response.json();if(!response.ok){setError(result.error);setBusy(false);return}setNetwork(result.network);setStep("network");setBusy(false)}
  return <main className="onboarding-page"><header><Link href="/"><span>n2</span>nice 2 network</Link><div><i className="done"/><i className="done"/><i className={step==="network"?"done":""}/></div><small>{step==="profile"?"2 of 3":"3 of 3"}</small></header>{step==="profile"?<section className="onboarding-card"><div className="verified-banner"><Check size={15}/><span><strong>Email verified</strong><small>Now let’s make your network useful.</small></span></div><span className="eyebrow">YOUR CONTRIBUTION</span><h1>What should people know you for?</h1><p>Rank three career skills so projects and people can find the contribution you make best.</p><form onSubmit={submit}><label>Profession<input name="profession" placeholder="e.g. Product designer" required minLength={2}/></label><label>Primary skill<input name="primarySkill" placeholder="e.g. Product strategy" required/><small>The skill you want to be known for.</small></label><label>Secondary skill<input name="secondarySkill" placeholder="e.g. User research" required/></label><label>Tertiary skill<input name="tertiarySkill" placeholder="e.g. Prototyping" required/></label><label>Interests<input name="interests" placeholder="Climate, local communities, public good" required/><small>What subjects or outcomes pull you in?</small></label><label>Location<div className="location-input"><MapPin size={16}/><input name="location" placeholder="London, UK" required/></div></label>{error&&<p className="form-error">{error}</p>}<button className="primary-button wide" disabled={busy}>{busy?"Building your network…":<>See my network <ArrowRight size={16}/></>}</button></form></section>:<section className="onboarding-card network-result"><span className="network-icon"><UsersRound size={23}/></span><span className="eyebrow">YOUR STARTING NETWORK</span><h1>You’re ready to make useful connections.</h1><p>{network.length?"These members share meaningful professional or personal overlap with you.":"Your profile is ready. Recommendations will appear as matching members and projects join the network."}</p>{network.length>0&&<div className="onboarding-network">{network.map(member=><article key={member.id}>{member.image&&<img src={member.image} alt=""/>}<span><strong>{member.name}</strong><small>{member.profession}{member.location?` · ${member.location}`:""}</small><i>{[...member.sharedSkills,...member.sharedInterests].slice(0,2).join(" · ")}</i></span><b>{member.score}</b></article>)}</div>}<Link className="primary-button wide" href="/signin">Complete sign up <ArrowRight size={16}/></Link></section>}</main>;
}
