"use client";
/* eslint-disable @next/next/no-img-element */

import { FormEvent, useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { Activity, AlertTriangle, ArrowLeft, BarChart3, BellRing, BriefcaseBusiness, CalendarDays, Check, ClipboardCheck, Database, FileClock, Flag, HeartHandshake, LayoutDashboard, Megaphone, MessageSquare, RefreshCw, Search, ShieldCheck, UserCog, UsersRound } from "lucide-react";

type Tab="overview"|"members"|"projects"|"activity"|"moderation"|"appeals"|"safety"|"analytics"|"audit"|"access"|"notices"|"system";
const navigation:[Tab,string,typeof LayoutDashboard][]=[["overview","Overview",LayoutDashboard],["members","Members",UsersRound],["projects","Projects & content",BriefcaseBusiness],["activity","Messages & meets",MessageSquare],["moderation","Moderation",Flag],["appeals","Appeals",ClipboardCheck],["safety","Teen safety",ShieldCheck],["analytics","Analytics",BarChart3],["audit","Audit log",FileClock],["access","Admin access",UserCog],["notices","Official notices",Megaphone],["system","System",Database]];
const labels:Record<Tab,[string,string]>={overview:["Operations overview","The health of the network, right now."],members:["Members","Support accounts and apply proportionate controls."],projects:["Projects & content","Review, quarantine or restore collaborative work."],activity:["Messages, posts & meets","Monitor adoption and service activity without reading private content."],moderation:["Moderation queue","Prioritise reports and preserve decisions."],appeals:["Appeals & complaints","Independent review of member outcomes."],safety:["Teen safety","Protected activity and safeguarding risks."],analytics:["Network analytics","Engagement, outcomes and safety performance."],audit:["Audit log","A traceable record of privileged activity."],access:["Administrator access","Assign internal roles without exposing them publicly."],notices:["Official n2 notices","Publish clearly branded network announcements."],system:["System health","Production services without secret exposure."]};
const endpoint:Record<Tab,string>={overview:"overview",members:"members",projects:"projects",activity:"activity",moderation:"moderation",appeals:"appeals",safety:"safety",analytics:"analytics",audit:"audit",access:"admins",notices:"notices",system:"system"};
const asRecord=(value:unknown):Record<string,unknown>=>value!==null&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};
const asRows=(value:unknown):Array<Record<string,unknown>>=>Array.isArray(value)?value.filter(item=>item!==null&&typeof item==="object") as Array<Record<string,unknown>>:[];

export default function AdminConsole({name,role}:{name:string;role:string}){
  const [tab,setTab]=useState<Tab>("overview");const [data,setData]=useState<Record<string,unknown>>({});const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [query,setQuery]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch(`/api/admin/${endpoint[tab]}${tab==="members"&&query?`?q=${encodeURIComponent(query)}`:""}`);if(response.status===428){window.location.href="/admin/access";return}const result=await response.json();if(!response.ok){setData({});setError(result.error??"Could not load this section.");return}setData(asRecord(result))}catch{setData({});setError("Could not load this section. Check your connection and try again.")}finally{setLoading(false)}},[tab,query]);
  useEffect(()=>{const frame=requestAnimationFrame(()=>void load());return()=>cancelAnimationFrame(frame)},[load]);
  async function action(url:string,body:Record<string,unknown>){const response=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const result=await response.json();if(!response.ok){setError(result.error);return}await load()}
  function selectTab(next:Tab){if(next===tab)return;setLoading(true);setError("");setData({});setTab(next)}
  return <main className="admin-shell"><aside className="admin-sidebar"><Link href="/" className="admin-brand"><span>n2</span><strong>nice 2 network</strong><i>ADMIN</i></Link><nav>{navigation.map(([id,label,Icon])=><button key={id} className={tab===id?"active":""} onClick={()=>selectTab(id)}><Icon size={17}/><span>{label}</span></button>)}</nav><div className="admin-user"><span>n2</span><div><strong>{name}</strong><small>{role.replaceAll("_"," ")}</small></div></div><Link className="admin-exit" href="/"><ArrowLeft size={15}/> Back to network</Link></aside><section className="admin-main"><header><div><span className="eyebrow">N2 OPERATIONS</span><h1>{labels[tab][0]}</h1><p>{labels[tab][1]}</p></div><button className="admin-refresh" onClick={load}><RefreshCw size={15}/> Refresh</button></header>{error&&<div className="admin-error"><AlertTriangle size={15}/>{error}</div>}{loading?<div className="admin-loading"><span/><p>Loading secure workspace…</p></div>:<AdminSection tab={tab} data={data} query={query} setQuery={setQuery} reload={load} action={action}/>}</section></main>;
}

function AdminSection({tab,data,query,setQuery,reload,action}:{tab:Tab;data:Record<string,unknown>;query:string;setQuery:(v:string)=>void;reload:()=>void;action:(url:string,body:Record<string,unknown>)=>Promise<void>}){
  if(tab==="activity") return <ActivityPanel data={data}/>;
  if(tab==="overview"){const metrics=asRecord(data.metrics);return <><div className="admin-metrics">{Object.entries(metrics).map(([key,value])=><article key={key}><span>{key.replace(/([A-Z])/g," $1")}</span><strong>{String(value)}</strong></article>)}</div><div className="admin-grid"><section className="admin-panel"><h3><Activity size={16}/> Operational focus</h3><div className="admin-focus"><span className="urgent"><strong>{String(metrics.urgentRisks??0)}</strong> urgent safety risks</span><span><strong>{String(metrics.openReports??0)}</strong> reports awaiting review</span><span><strong>{String(metrics.openAppeals??0)}</strong> open appeals</span></div></section><section className="admin-panel"><h3><HeartHandshake size={16}/> Network motion</h3><div className="admin-focus"><span><strong>{String(metrics.pendingApplications??0)}</strong> pending applications</span><span><strong>{String(metrics.openRoles??0)}</strong> open project roles</span><span><strong>{String(metrics.upcomingMeets??0)}</strong> upcoming meets</span></div></section></div></>}
  if(tab==="members"){
    const members=asRows(data.members);
    return <><form className="admin-search" onSubmit={e=>{e.preventDefault();reload()}}><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, email or profession"/><button>Search</button></form><div className="admin-table">{members.map(member=><article key={String(member.id)}><AvatarCell image={member.image as string|null} name={String(member.name??"Member")} admin={member.adminStatus==="active"}/><span><strong>{String(member.email)}</strong><small>{String(member.profession??"Profile incomplete")} · {String(member.ageBand).replaceAll("_"," ")}</small></span><Status value={String(member.status)}/><select aria-label={`Action for ${member.name}`} defaultValue=""><option value="" disabled>Action</option><option value="resend_verification">Resend verification</option><option value="trigger_recovery">Send password recovery</option><option value="warn">Warn</option><option value="restrict_messaging">Restrict messages</option><option value="restrict_invitations">Restrict invitations</option><option value="restrict_meetings">Restrict meetings</option><option value="suspend">Suspend</option><option value="ban">Ban</option><option value="reactivate">Reactivate</option><option value="expire_sessions">Expire sessions</option></select><button onClick={e=>{const select=e.currentTarget.previousElementSibling as HTMLSelectElement;if(!select.value)return;const reason=window.prompt("Record the reason for this action (minimum 10 characters):");if(reason)action(`/api/admin/members/${member.id}/action`,{action:select.value,reason,policyCode:"community_standards"})}}>Apply</button></article>)}</div></>
  }
  if(tab==="projects"){const rows=asRows(data.projects);return <div className="admin-table">{rows.map(row=><article key={String(row.id)}><span className="project-admin-icon"><BriefcaseBusiness size={17}/></span><span><strong>{String(row.title)}</strong><small>{String(row.ownerName)} · {String(row.industry)} · {String(row.stage)}</small></span><Status value={String(row.status)}/><select defaultValue=""><option value="" disabled>Action</option><option value="quarantine">Quarantine</option><option value="restore">Restore</option><option value="pause_applications">Pause applications</option><option value="close_roles">Close roles</option><option value="transfer_ownership">Transfer ownership</option></select><button onClick={e=>{const select=e.currentTarget.previousElementSibling as HTMLSelectElement;if(!select.value)return;const reason=window.prompt("Record the reason:");const newOwnerId=select.value==="transfer_ownership"?window.prompt("New owner member ID:"):undefined;if(reason)action(`/api/admin/projects/${row.id}/action`,{action:select.value,reason,newOwnerId})}}>Apply</button></article>)}</div>}
  if(tab==="moderation"){const rows=asRows(data.reports);return <div className="case-grid">{rows.map(row=><article key={String(row.id)}><div><Status value={String(row.priority)}/><small>{new Date(String(row.createdAt)).toLocaleString()}</small></div><h3>{String(row.reason).replaceAll("_"," ")}</h3><p>{String(row.details??"No additional details supplied.")}</p><footer><span>{String(row.targetType)} · reported by {String(row.reporterName)}</span><button onClick={()=>action(`/api/admin/moderation/${row.id}`,{action:"investigate",note:"Investigation opened from moderation queue"})}>Investigate</button><button onClick={()=>action(`/api/admin/moderation/${row.id}`,{action:"snapshot",note:"Evidence snapshot preserved"})}>Preserve</button></footer></article>)}</div>}
  if(tab==="analytics"){const summary=asRecord(data.summary),top=asRows(data.topProjects),events=asRows(data.events);return <><div className="admin-metrics">{Object.entries(summary).map(([key,value])=><article key={key}><span>{key.replace(/([A-Z])/g," $1")}</span><strong>{String(value)}</strong></article>)}</div><div className="admin-grid"><section className="admin-panel"><h3>Most engaged projects</h3>{top.map(row=><div className="rank-row" key={String(row.id)}><span>{String(row.title)}</span><strong>{String(row.engagement)}</strong></div>)}</section><section className="admin-panel"><h3>Product events · 30 days</h3>{events.map(row=><div className="rank-row" key={String(row.event)}><span>{String(row.event).replaceAll("_"," ")}</span><strong>{String(row.value)}</strong></div>)}</section></div></>}
  if(tab==="access"){const rows=asRows(data.administrators);return <><AdminAssignmentForm onSave={body=>action("/api/admin/admins",body)}/><div className="admin-table">{rows.map(row=><article key={String(row.id)}><AvatarCell image={row.image as string|null} name={String(row.name??"Administrator")} admin={row.status==="active"}/><span><strong>{String(row.name??row.email)}</strong><small>{String(row.email)} · {String(row.role).replaceAll("_"," ")}</small></span><Status value={String(row.status)}/><span/><span/></article>)}</div></>}
  if(tab==="audit"){const rows=asRows(data.audit);return <div className="audit-list">{rows.map(row=><article key={String(row.id)}><span/><div><strong>{String(row.action).replaceAll("_"," ")}</strong><small>{String(row.actorName??"System")} · {String(row.targetType)} {String(row.targetId??"")} · {new Date(String(row.createdAt)).toLocaleString()}</small>{Boolean(row.reason)&&<p>{String(row.reason)}</p>}</div><Status value={String(row.severity)}/></article>)}</div>}
  if(tab==="notices"){const notices=asRows(data.notices);return <><NoticeForm onCreate={body=>action("/api/admin/notices",body)}/><div className="notice-list">{notices.map(row=><article key={String(row.id)}><span className="official-badge"><b>n2</b> OFFICIAL NOTICE</span><h3>{String(row.title)}</h3><p>{String(row.body)}</p><small>{String(row.audience)} · {new Date(String(row.publishedAt)).toLocaleString()}</small></article>)}</div></>}
  if(tab==="system") return <SystemPanel health={data}/>;
  const key=tab==="appeals"?"appeals":"risks",rows=asRows(data[key]);return rows.length?<div className="case-grid">{rows.map(row=><article key={String(row.id)}><div><Status value={String(row.status)}/>{Boolean(row.severity)&&<Status value={String(row.severity)}/>}</div><h3>{String(row.type??row.appellantName??"Case")}</h3><p>{String(row.statement??JSON.stringify(row.details??{}))}</p><small>{new Date(String(row.createdAt)).toLocaleString()}</small>{tab==="appeals"&&row.status==="open"&&<footer><span>Independent review required</span><button onClick={()=>{const reason=window.prompt("Reason for upholding this decision:");if(reason)action("/api/admin/appeals",{appealId:row.id,decision:"upheld",reason})}}>Uphold</button><button onClick={()=>{const reason=window.prompt("Reason for overturning this decision:");if(reason)action("/api/admin/appeals",{appealId:row.id,decision:"overturned",reason})}}>Overturn</button></footer>}</article>)}</div>:<Empty title={tab==="appeals"?"No open appeals":"No active teen-safety risks"}/>;
}

function ActivityPanel({data}:{data:Record<string,unknown>}){
  const metrics=asRecord(data.metrics),profiles=asRecord(data.profileAdoption),meets=asRows(data.recentMeetings),chats=asRows(data.recentConversations);
  return <>
    <div className="admin-metrics">{Object.entries(metrics).map(([key,value])=><article key={key}><span>{key.replace(/([A-Z])/g," $1")}</span><strong>{String(value)}</strong></article>)}</div>
    <div className="admin-grid">
      <section className="admin-panel"><h3><UsersRound size={16}/> Profile adoption</h3><div className="admin-focus">{Object.entries(profiles).map(([key,value])=><span key={key}>{key.replace(/([A-Z])/g," $1")}<strong>{String(value)}</strong></span>)}</div></section>
      <section className="admin-panel"><h3><CalendarDays size={16}/> Upcoming meets</h3><div className="admin-activity-list">{meets.map(meet=><article key={String(meet.id)}><span><CalendarDays size={15}/></span><div><strong>{String(meet.title)}</strong><small>{String(meet.creator??"n2 member")} · {new Date(String(meet.startsAt)).toLocaleString()}</small></div><Status value={String(meet.provider)}/></article>)}{!meets.length&&<Empty title="No upcoming meets"/>}</div></section>
      <section className="admin-panel"><h3><MessageSquare size={16}/> Recent conversation activity</h3><div className="admin-activity-list">{chats.map(chat=><article key={String(chat.id)}><span><MessageSquare size={15}/></span><div><strong>{String(chat.name??"Direct conversation")}</strong><small>{String(chat.member_count)} members · {String(chat.message_count)} messages · updated {new Date(String(chat.updated_at)).toLocaleString()}</small></div><Status value="active"/></article>)}{!chats.length&&<Empty title="No conversations yet"/>}</div></section>
      <section className="admin-panel"><h3><ShieldCheck size={16}/> Privacy boundary</h3><p className="admin-privacy-note"><ShieldCheck size={16}/>{String(data.privacyNote)}</p><div className="admin-focus"><span>Private message bodies<strong>Hidden</strong></span><span>Reported evidence<strong>Case access only</strong></span><span>Live typing data<strong>Count only</strong></span></div></section>
    </div>
  </>;
}

function AvatarCell({image,name,admin}:{image:string|null;name:string;admin:boolean}){return <span className="admin-avatar">{image?<img src={image} alt=""/>:<b>n2</b>}<i>{name.slice(0,1)}</i>{admin&&<em><b>n2</b> ADMIN</em>}</span>}
function Status({value}:{value:string}){return <span className={`admin-status status-${value}`}>{value.replaceAll("_"," ")}</span>}
function Empty({title}:{title:string}){return <div className="admin-empty"><Check size={23}/><strong>{title}</strong><p>The queue is clear right now.</p></div>}
function SystemPanel({health}:{health:Record<string,unknown>}){
  const [settings,setSettings]=useState<{provider:string;blueprintModel:string;embeddingModel:string;rolloutStage:number;weights:Record<string,number>}|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  useEffect(()=>{fetch("/api/admin/recommendations/settings").then(response=>response.json()).then(result=>setSettings(result.settings??null)).catch(()=>setMessage("Recommendation controls could not be loaded."))},[]);
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!settings)return;const reason=window.prompt("Record why this algorithm version should be activated (minimum 10 characters):");if(!reason)return;setBusy(true);const response=await fetch("/api/admin/recommendations/settings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...settings,reason})});const result=await response.json();setMessage(response.ok?`Version ${result.settings.version} activated.`:result.error??"Could not activate settings.");if(response.ok)setSettings({...settings,...result.settings});setBusy(false)}
  async function reindex(){const reason=window.prompt("Record why embeddings should be rebuilt (minimum 10 characters):");if(!reason)return;setBusy(true);const response=await fetch("/api/admin/recommendations/reindex",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({reason,batchSize:20})});const result=await response.json();setMessage(response.ok?`Embedding rebuild ${result.job.status}: ${result.job.processed}/${result.job.total}.`:result.error??"Could not start the rebuild.");setBusy(false)}
  return <><div className="system-grid">{Object.entries(health).filter(([key])=>!["generatedAt","recommendationJobs"].includes(key)).map(([key,value])=><article key={key}><span>{key.replace(/([A-Z])/g," $1")}</span><Status value={String(value)}/></article>)}</div>{settings&&<form className="algorithm-settings" onSubmit={save}><header><div><span className="official-badge"><b>n2</b> TEAM ENGINE</span><h3>Recommendation controls</h3><p>Activate one provider and one versioned configuration. Providers never fail over automatically.</p></div><Status value={`stage_${settings.rolloutStage}`}/></header><div className="algorithm-fields"><label>Active provider<select value={settings.provider} onChange={event=>setSettings({...settings,provider:event.target.value})}><option value="openai">OpenAI</option><option value="gemini">Gemini</option></select></label><label>Rollout stage<select value={settings.rolloutStage} onChange={event=>setSettings({...settings,rolloutStage:Number(event.target.value)})}><option value={1}>1 · Shadow mode</option><option value={2}>2 · Adult For You</option><option value={3}>3 · High-confidence alerts</option></select></label><label>Blueprint model<input value={settings.blueprintModel} onChange={event=>setSettings({...settings,blueprintModel:event.target.value})}/></label><label>Embedding model<input value={settings.embeddingModel} onChange={event=>setSettings({...settings,embeddingModel:event.target.value})}/></label></div><div className="algorithm-actions"><button type="button" onClick={reindex} disabled={busy}><RefreshCw size={15}/> Rebuild embeddings</button><button className="primary-button" disabled={busy}>Activate new version</button></div>{message&&<p>{message}</p>}</form>}</>;
}
function NoticeForm({onCreate}:{onCreate:(body:Record<string,unknown>)=>Promise<void>}){async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);await onCreate({title:data.get("title"),body:data.get("body"),audience:data.get("audience")});form.reset()}return <form className="notice-form" onSubmit={submit}><div><span className="official-badge"><b>n2</b> OFFICIAL NOTICE</span><h3>Publish to the network</h3></div><input name="title" placeholder="Notice title" required minLength={4}/><textarea name="body" placeholder="Clear, useful information from the n2 team…" required minLength={10}/><div><select name="audience"><option value="all">All members</option><option value="adults">Adults</option><option value="teens">16–17 members</option></select><button className="primary-button"><BellRing size={15}/> Publish notice</button></div></form>}
function AdminAssignmentForm({onSave}:{onSave:(body:Record<string,unknown>)=>Promise<void>}){async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);await onSave({userId:data.get("userId"),role:data.get("role"),status:data.get("status"),reason:data.get("reason")});form.reset()}return <form className="notice-form" onSubmit={submit}><div><span className="official-badge"><b>n2</b> ADMIN ACCESS</span><h3>Assign or change an internal role</h3></div><input name="userId" placeholder="Member ID" required/><input name="reason" placeholder="Written reason (minimum 10 characters)" required minLength={10}/><div><select name="role"><option value="support_admin">Support admin</option><option value="safety_admin">Safety admin</option><option value="analyst">Analyst</option><option value="super_admin">Super admin</option></select><select name="status"><option value="active">Active</option><option value="suspended">Suspended</option><option value="revoked">Revoked</option></select><button className="primary-button"><ShieldCheck size={15}/> Save access</button></div></form>}
