"use client";
/* eslint-disable @next/next/no-img-element */

import { FormEvent, useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { Activity, AlertTriangle, ArrowLeft, BarChart3, BellRing, BriefcaseBusiness, Check, ClipboardCheck, Database, FileClock, Flag, HeartHandshake, LayoutDashboard, Megaphone, RefreshCw, Search, ShieldCheck, UserCog, UsersRound } from "lucide-react";

type Tab="overview"|"members"|"projects"|"moderation"|"appeals"|"safety"|"analytics"|"audit"|"access"|"notices"|"system";
const navigation:[Tab,string,typeof LayoutDashboard][]=[["overview","Overview",LayoutDashboard],["members","Members",UsersRound],["projects","Projects & content",BriefcaseBusiness],["moderation","Moderation",Flag],["appeals","Appeals",ClipboardCheck],["safety","Teen safety",ShieldCheck],["analytics","Analytics",BarChart3],["audit","Audit log",FileClock],["access","Admin access",UserCog],["notices","Official notices",Megaphone],["system","System",Database]];
const labels:Record<Tab,[string,string]>={overview:["Operations overview","The health of the network, right now."],members:["Members","Support accounts and apply proportionate controls."],projects:["Projects & content","Review, quarantine or restore collaborative work."],moderation:["Moderation queue","Prioritise reports and preserve decisions."],appeals:["Appeals & complaints","Independent review of member outcomes."],safety:["Teen safety","Protected activity and safeguarding risks."],analytics:["Network analytics","Engagement, outcomes and safety performance."],audit:["Audit log","A traceable record of privileged activity."],access:["Administrator access","Assign internal roles without exposing them publicly."],notices:["Official n2 notices","Publish clearly branded network announcements."],system:["System health","Production services without secret exposure."]};
const endpoint:Record<Tab,string>={overview:"overview",members:"members",projects:"projects",moderation:"moderation",appeals:"appeals",safety:"safety",analytics:"analytics",audit:"audit",access:"admins",notices:"notices",system:"system"};

export default function AdminConsole({name,role}:{name:string;role:string}){
  const [tab,setTab]=useState<Tab>("overview");const [data,setData]=useState<Record<string,unknown>>({});const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [query,setQuery]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");const response=await fetch(`/api/admin/${endpoint[tab]}${tab==="members"&&query?`?q=${encodeURIComponent(query)}`:""}`);if(response.status===428){window.location.href="/admin/access";return}const result=await response.json();if(!response.ok){setError(result.error??"Could not load this section.");setLoading(false);return}setData(result);setLoading(false)},[tab,query]);
  useEffect(()=>{const frame=requestAnimationFrame(()=>void load());return()=>cancelAnimationFrame(frame)},[load]);
  async function action(url:string,body:Record<string,unknown>){const response=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const result=await response.json();if(!response.ok){setError(result.error);return}await load()}
  return <main className="admin-shell"><aside className="admin-sidebar"><Link href="/" className="admin-brand"><span>n2</span><strong>nice 2 network</strong><i>ADMIN</i></Link><nav>{navigation.map(([id,label,Icon])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><Icon size={17}/><span>{label}</span></button>)}</nav><div className="admin-user"><span>n2</span><div><strong>{name}</strong><small>{role.replaceAll("_"," ")}</small></div></div><Link className="admin-exit" href="/"><ArrowLeft size={15}/> Back to network</Link></aside><section className="admin-main"><header><div><span className="eyebrow">N2 OPERATIONS</span><h1>{labels[tab][0]}</h1><p>{labels[tab][1]}</p></div><button className="admin-refresh" onClick={load}><RefreshCw size={15}/> Refresh</button></header>{error&&<div className="admin-error"><AlertTriangle size={15}/>{error}</div>}{loading?<div className="admin-loading"><span/><p>Loading secure workspace…</p></div>:<AdminSection tab={tab} data={data} query={query} setQuery={setQuery} reload={load} action={action}/>}</section></main>;
}

function AdminSection({tab,data,query,setQuery,reload,action}:{tab:Tab;data:Record<string,unknown>;query:string;setQuery:(v:string)=>void;reload:()=>void;action:(url:string,body:Record<string,unknown>)=>Promise<void>}){
  if(tab==="overview"){const metrics=data.metrics as Record<string,number>;return <><div className="admin-metrics">{Object.entries(metrics).map(([key,value])=><article key={key}><span>{key.replace(/([A-Z])/g," $1")}</span><strong>{value}</strong></article>)}</div><div className="admin-grid"><section className="admin-panel"><h3><Activity size={16}/> Operational focus</h3><div className="admin-focus"><span className="urgent"><strong>{metrics.urgentRisks}</strong> urgent safety risks</span><span><strong>{metrics.openReports}</strong> reports awaiting review</span><span><strong>{metrics.openAppeals}</strong> open appeals</span></div></section><section className="admin-panel"><h3><HeartHandshake size={16}/> Network motion</h3><div className="admin-focus"><span><strong>{metrics.pendingApplications}</strong> pending applications</span><span><strong>{metrics.openRoles}</strong> open project roles</span><span><strong>{metrics.upcomingMeets}</strong> upcoming meets</span></div></section></div></>}
  if(tab==="members"){
    const members=data.members as Array<Record<string,unknown>>;
    return <><form className="admin-search" onSubmit={e=>{e.preventDefault();reload()}}><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, email or profession"/><button>Search</button></form><div className="admin-table">{members.map(member=><article key={String(member.id)}><AvatarCell image={member.image as string|null} name={String(member.name??"Member")} admin={member.adminStatus==="active"}/><span><strong>{String(member.email)}</strong><small>{String(member.profession??"Profile incomplete")} · {String(member.ageBand).replaceAll("_"," ")}</small></span><Status value={String(member.status)}/><select aria-label={`Action for ${member.name}`} defaultValue=""><option value="" disabled>Action</option><option value="resend_verification">Resend verification</option><option value="trigger_recovery">Send password recovery</option><option value="warn">Warn</option><option value="restrict_messaging">Restrict messages</option><option value="restrict_invitations">Restrict invitations</option><option value="restrict_meetings">Restrict meetings</option><option value="suspend">Suspend</option><option value="ban">Ban</option><option value="reactivate">Reactivate</option><option value="expire_sessions">Expire sessions</option></select><button onClick={e=>{const select=e.currentTarget.previousElementSibling as HTMLSelectElement;if(!select.value)return;const reason=window.prompt("Record the reason for this action (minimum 10 characters):");if(reason)action(`/api/admin/members/${member.id}/action`,{action:select.value,reason,policyCode:"community_standards"})}}>Apply</button></article>)}</div></>
  }
  if(tab==="projects"){const rows=data.projects as Array<Record<string,unknown>>;return <div className="admin-table">{rows.map(row=><article key={String(row.id)}><span className="project-admin-icon"><BriefcaseBusiness size={17}/></span><span><strong>{String(row.title)}</strong><small>{String(row.ownerName)} · {String(row.industry)} · {String(row.stage)}</small></span><Status value={String(row.status)}/><select defaultValue=""><option value="" disabled>Action</option><option value="quarantine">Quarantine</option><option value="restore">Restore</option><option value="pause_applications">Pause applications</option><option value="close_roles">Close roles</option><option value="transfer_ownership">Transfer ownership</option></select><button onClick={e=>{const select=e.currentTarget.previousElementSibling as HTMLSelectElement;if(!select.value)return;const reason=window.prompt("Record the reason:");const newOwnerId=select.value==="transfer_ownership"?window.prompt("New owner member ID:"):undefined;if(reason)action(`/api/admin/projects/${row.id}/action`,{action:select.value,reason,newOwnerId})}}>Apply</button></article>)}</div>}
  if(tab==="moderation"){const rows=data.reports as Array<Record<string,unknown>>;return <div className="case-grid">{rows.map(row=><article key={String(row.id)}><div><Status value={String(row.priority)}/><small>{new Date(String(row.createdAt)).toLocaleString()}</small></div><h3>{String(row.reason).replaceAll("_"," ")}</h3><p>{String(row.details??"No additional details supplied.")}</p><footer><span>{String(row.targetType)} · reported by {String(row.reporterName)}</span><button onClick={()=>action(`/api/admin/moderation/${row.id}`,{action:"investigate",note:"Investigation opened from moderation queue"})}>Investigate</button><button onClick={()=>action(`/api/admin/moderation/${row.id}`,{action:"snapshot",note:"Evidence snapshot preserved"})}>Preserve</button></footer></article>)}</div>}
  if(tab==="analytics"){const summary=data.summary as Record<string,number>,top=data.topProjects as Array<Record<string,unknown>>,events=data.events as Array<Record<string,unknown>>;return <><div className="admin-metrics">{Object.entries(summary).map(([key,value])=><article key={key}><span>{key.replace(/([A-Z])/g," $1")}</span><strong>{value}</strong></article>)}</div><div className="admin-grid"><section className="admin-panel"><h3>Most engaged projects</h3>{top.map(row=><div className="rank-row" key={String(row.id)}><span>{String(row.title)}</span><strong>{String(row.engagement)}</strong></div>)}</section><section className="admin-panel"><h3>Product events · 30 days</h3>{events.map(row=><div className="rank-row" key={String(row.event)}><span>{String(row.event).replaceAll("_"," ")}</span><strong>{String(row.value)}</strong></div>)}</section></div></>}
  if(tab==="access"){const rows=data.administrators as Array<Record<string,unknown>>;return <><AdminAssignmentForm onSave={body=>action("/api/admin/admins",body)}/><div className="admin-table">{rows.map(row=><article key={String(row.id)}><AvatarCell image={row.image as string|null} name={String(row.name??"Administrator")} admin={row.status==="active"}/><span><strong>{String(row.name??row.email)}</strong><small>{String(row.email)} · {String(row.role).replaceAll("_"," ")}</small></span><Status value={String(row.status)}/><span/><span/></article>)}</div></>}
  if(tab==="audit"){const rows=data.audit as Array<Record<string,unknown>>;return <div className="audit-list">{rows.map(row=><article key={String(row.id)}><span/><div><strong>{String(row.action).replaceAll("_"," ")}</strong><small>{String(row.actorName??"System")} · {String(row.targetType)} {String(row.targetId??"")} · {new Date(String(row.createdAt)).toLocaleString()}</small>{Boolean(row.reason)&&<p>{String(row.reason)}</p>}</div><Status value={String(row.severity)}/></article>)}</div>}
  if(tab==="notices"){const notices=data.notices as Array<Record<string,unknown>>;return <><NoticeForm onCreate={body=>action("/api/admin/notices",body)}/><div className="notice-list">{notices.map(row=><article key={String(row.id)}><span className="official-badge"><b>n2</b> OFFICIAL NOTICE</span><h3>{String(row.title)}</h3><p>{String(row.body)}</p><small>{String(row.audience)} · {new Date(String(row.publishedAt)).toLocaleString()}</small></article>)}</div></>}
  if(tab==="system"){return <div className="system-grid">{Object.entries(data).filter(([key])=>key!=="generatedAt").map(([key,value])=><article key={key}><span>{key}</span><Status value={String(value)}/></article>)}</div>}
  const key=tab==="appeals"?"appeals":"risks",rows=(data[key]??[]) as Array<Record<string,unknown>>;return rows.length?<div className="case-grid">{rows.map(row=><article key={String(row.id)}><div><Status value={String(row.status)}/>{Boolean(row.severity)&&<Status value={String(row.severity)}/>}</div><h3>{String(row.type??row.appellantName??"Case")}</h3><p>{String(row.statement??JSON.stringify(row.details??{}))}</p><small>{new Date(String(row.createdAt)).toLocaleString()}</small>{tab==="appeals"&&row.status==="open"&&<footer><span>Independent review required</span><button onClick={()=>{const reason=window.prompt("Reason for upholding this decision:");if(reason)action("/api/admin/appeals",{appealId:row.id,decision:"upheld",reason})}}>Uphold</button><button onClick={()=>{const reason=window.prompt("Reason for overturning this decision:");if(reason)action("/api/admin/appeals",{appealId:row.id,decision:"overturned",reason})}}>Overturn</button></footer>}</article>)}</div>:<Empty title={tab==="appeals"?"No open appeals":"No active teen-safety risks"}/>;
}

function AvatarCell({image,name,admin}:{image:string|null;name:string;admin:boolean}){return <span className="admin-avatar">{image?<img src={image} alt=""/>:<b>n2</b>}<i>{name.slice(0,1)}</i>{admin&&<em><b>n2</b> ADMIN</em>}</span>}
function Status({value}:{value:string}){return <span className={`admin-status status-${value}`}>{value.replaceAll("_"," ")}</span>}
function Empty({title}:{title:string}){return <div className="admin-empty"><Check size={23}/><strong>{title}</strong><p>The queue is clear right now.</p></div>}
function NoticeForm({onCreate}:{onCreate:(body:Record<string,unknown>)=>Promise<void>}){async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);await onCreate({title:data.get("title"),body:data.get("body"),audience:data.get("audience")});form.reset()}return <form className="notice-form" onSubmit={submit}><div><span className="official-badge"><b>n2</b> OFFICIAL NOTICE</span><h3>Publish to the network</h3></div><input name="title" placeholder="Notice title" required minLength={4}/><textarea name="body" placeholder="Clear, useful information from the n2 team…" required minLength={10}/><div><select name="audience"><option value="all">All members</option><option value="adults">Adults</option><option value="teens">16–17 members</option></select><button className="primary-button"><BellRing size={15}/> Publish notice</button></div></form>}
function AdminAssignmentForm({onSave}:{onSave:(body:Record<string,unknown>)=>Promise<void>}){async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);await onSave({userId:data.get("userId"),role:data.get("role"),status:data.get("status"),reason:data.get("reason")});form.reset()}return <form className="notice-form" onSubmit={submit}><div><span className="official-badge"><b>n2</b> ADMIN ACCESS</span><h3>Assign or change an internal role</h3></div><input name="userId" placeholder="Member ID" required/><input name="reason" placeholder="Written reason (minimum 10 characters)" required minLength={10}/><div><select name="role"><option value="support_admin">Support admin</option><option value="safety_admin">Safety admin</option><option value="analyst">Analyst</option><option value="super_admin">Super admin</option></select><select name="status"><option value="active">Active</option><option value="suspended">Suspended</option><option value="revoked">Revoked</option></select><button className="primary-button"><ShieldCheck size={15}/> Save access</button></div></form>}
