/* eslint-disable no-empty, @next/next/no-html-link-for-pages, jsx-a11y/media-has-caption, react-hooks/purity, react-hooks/refs */
"use client";
import { Mic,MicOff,PhoneOff,Video,VideoOff } from "lucide-react";import { useEffect,useRef,useState } from "react";import { useParams } from "next/navigation";
type Signal={id:string;senderId:string;recipientId?:string|null;type:"join"|"heartbeat"|"offer"|"answer"|"ice"|"leave";payload:Record<string,unknown>;createdAt:string};
export default function N2MeetRoom(){const {meetingId}=useParams<{meetingId:string}>(),localVideo=useRef<HTMLVideoElement>(null),localStream=useRef<MediaStream|null>(null),peers=useRef(new Map<string,RTCPeerConnection>()),[remoteStreams,setRemoteStreams]=useState<Array<{id:string;stream:MediaStream}>>([]),[title,setTitle]=useState("n2 meet"),[error,setError]=useState(""),[muted,setMuted]=useState(false),[cameraOff,setCameraOff]=useState(false),[ready,setReady]=useState(false);const lastPoll=useRef(0);
  if(!lastPoll.current&&typeof window!=="undefined")lastPoll.current=window.performance.timeOrigin+window.performance.now()-5000;
  async function signal(type:Signal["type"],payload:Record<string,unknown>={},recipientId?:string){const response=await fetch(`/api/meetings/${meetingId}/signals`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type,payload,recipientId})});if(!response.ok){const data=await response.json();throw new Error(data.error??"Room unavailable")}}
  function peer(id:string){let pc=peers.current.get(id);if(pc)return pc;pc=new RTCPeerConnection({iceServers:[{urls:"stun:stun.l.google.com:19302"}]});localStream.current?.getTracks().forEach(track=>pc!.addTrack(track,localStream.current!));pc.onicecandidate=event=>event.candidate&&signal("ice",{candidate:event.candidate.toJSON()},id).catch(()=>undefined);pc.ontrack=event=>setRemoteStreams(rows=>rows.some(row=>row.id===id)?rows.map(row=>row.id===id?{id,stream:event.streams[0]}:row):[...rows,{id,stream:event.streams[0]}]);pc.onconnectionstatechange=()=>{if(["closed","failed","disconnected"].includes(pc!.connectionState))setRemoteStreams(rows=>rows.filter(row=>row.id!==id))};peers.current.set(id,pc);return pc}
  async function handle(item:Signal){const pc=peer(item.senderId);if(item.type==="join"){const offer=await pc.createOffer();await pc.setLocalDescription(offer);await signal("offer",{sdp:offer},item.senderId)}if(item.type==="offer"){await pc.setRemoteDescription(item.payload.sdp as RTCSessionDescriptionInit);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await signal("answer",{sdp:answer},item.senderId)}if(item.type==="answer")await pc.setRemoteDescription(item.payload.sdp as RTCSessionDescriptionInit);if(item.type==="ice"&&item.payload.candidate)await pc.addIceCandidate(item.payload.candidate as RTCIceCandidateInit);if(item.type==="leave"){pc.close();peers.current.delete(item.senderId);setRemoteStreams(rows=>rows.filter(row=>row.id!==item.senderId))}}
  useEffect(()=>{let timer:ReturnType<typeof setInterval>,heartbeat:ReturnType<typeof setInterval>;async function start(){try{const [meetingResponse,stream]=await Promise.all([fetch(`/api/meetings/${meetingId}`),navigator.mediaDevices.getUserMedia({audio:true,video:true})]);if(!meetingResponse.ok)throw new Error("Meet not found");const data=await meetingResponse.json();setTitle(data.meeting.title);localStream.current=stream;if(localVideo.current)localVideo.current.srcObject=stream;await signal("join",{});setReady(true);heartbeat=setInterval(()=>signal("heartbeat",{}).catch(()=>undefined),20000);timer=setInterval(async()=>{const response=await fetch(`/api/meetings/${meetingId}/signals?since=${lastPoll.current}`);if(!response.ok)return;const data=await response.json();lastPoll.current=data.serverTime;for(const item of data.signals as Signal[])try{await handle(item)}catch{}},1300)}catch(cause){setError(cause instanceof Error?cause.message:"Camera and microphone access is required")}}start();return()=>{clearInterval(timer);clearInterval(heartbeat);signal("leave",{}).catch(()=>undefined);peers.current.forEach(pc=>pc.close());localStream.current?.getTracks().forEach(track=>track.stop())}},[meetingId]);
  function toggle(kind:"audio"|"video"){const track=localStream.current?.getTracks().find(item=>item.kind===kind);if(track)track.enabled=!track.enabled;if(kind==="audio")setMuted(value=>!value);else setCameraOff(value=>!value)}function leave(){signal("leave",{}).catch(()=>undefined);window.location.href="/?view=meet"}
  return <main className="video-room"><header><a href="/"><span>n2</span>nice 2 network</a><div><strong>{title}</strong><small>{1+remoteStreams.length}/4 people · encrypted peer-to-peer demo room</small></div><button onClick={leave}>Leave</button></header>{error?<section className="video-room-error"><VideoOff size={28}/><h1>Could not join this room</h1><p>{error}</p><button onClick={()=>history.back()}>Go back</button></section>:<section className="video-grid"><article><video ref={localVideo} autoPlay playsInline muted/><span>You</span></article>{remoteStreams.map(row=><RemoteVideo key={row.id} stream={row.stream}/>)}{ready&&Array.from({length:Math.max(0,4-remoteStreams.length-1)},(_,index)=><article className="empty-video" key={index}><span>Waiting for someone useful…</span></article>)}</section>}<footer><button className={muted?"off":""} onClick={()=>toggle("audio")}>{muted?<MicOff/>:<Mic/>}</button><button className={cameraOff?"off":""} onClick={()=>toggle("video")}>{cameraOff?<VideoOff/>:<Video/>}</button><button className="hangup" onClick={leave}><PhoneOff/></button></footer></main>}
function RemoteVideo({stream}:{stream:MediaStream}){const ref=useRef<HTMLVideoElement>(null);useEffect(()=>{if(ref.current)ref.current.srcObject=stream},[stream]);return <article><video ref={ref} autoPlay playsInline/><span>n2 member</span></article>}
