import type { Metadata } from "next";
import { LegalPage } from "@/components/public-site-shell";

export const metadata: Metadata = {
  title: "Privacy — nice 2 network",
  description: "How nice 2 network collects, uses, shares and protects personal information.",
};

export default function PrivacyPage() {
  return <LegalPage eyebrow="PRIVACY / YOUR CHOICES" title="Privacy, in plain language." summary="This notice explains what information nice 2 network uses, why we use it, who may receive it, how long we keep it and the choices available to you.">
    <section><h2>1. Who this notice is for</h2><p>This notice applies when you visit, join or use nice 2 network, including its profiles, project spaces, recommendations, posts, messages, meetings, applications, reports and account settings. In this notice, “we”, “us” and “the network” mean nice 2 network.</p><p>nice 2 network was created by its founders and built in partnership with IntAillium. Use the in-product Help area to contact us about privacy, exercise a data right or ask who is responsible for a particular use of your information.</p></section>

    <section><h2>2. Information you give us</h2><p>Account and profile information may include your name, email address, password credentials, profile image, profession, biography, career history, skills, interests, availability, working preferences, city, country and timezone. You choose how complete to make your profile, subject to the information required to create and secure an account.</p><p>We also store content and activity you intentionally create: projects, roles, applications, milestones, updates, posts, comments, reactions, saved items, follows, invitations, messages, meeting details, files, reports, appeals, settings and support requests.</p><p>Please avoid placing highly sensitive or unnecessary personal information in public profile fields, posts or project descriptions. Information shared with another member may be copied or used by that person outside the service.</p></section>

    <section><h2>3. Information created through use</h2><p>We create service records when you use the network. These may include sign-in and security events, timestamps, device and browser details, approximate network information, feature usage, notification state, recommendation feedback and audit records.</p><p>Messages may generate delivery, read and typing-status records. Meetings may generate invitations, attendance, timing, chat or podcast records depending on the features used. We minimise what administrators can see: ordinary administrative views do not expose private message bodies, although authorised reviewers may access reported material where necessary to investigate a safety case.</p></section>

    <section><h2>4. Information from other sources</h2><p>Other members may provide information about you when they invite you to a project, mention you, submit a report or include you in a meeting. We may receive limited account, calendar or meeting information from Google or Microsoft when you choose to connect those services.</p><p>We may also receive technical and security information from hosting, email-delivery, analytics and fraud-prevention suppliers. When information comes from another source, we use it only for the purpose for which it was supplied and in accordance with this notice.</p></section>

    <section><h2>5. How and why we use information</h2><p>We use information to create and secure accounts; display profiles and content to the selected audience; operate projects, applications, messages and meetings; deliver notifications; provide support; prevent abuse; investigate reports; maintain records; and improve the reliability and accessibility of the service.</p><p>We may process information because it is needed to provide the service you requested, because you have given consent, because we must meet a legal obligation, or because we have a legitimate interest in operating a safe, useful and sustainable network. Where we rely on legitimate interests, we consider the impact on members and apply privacy controls appropriate to the use.</p><p>Where a use depends on consent—such as optional analytics—you may withdraw that consent. Withdrawal does not affect processing that was lawful before it was withdrawn.</p></section>

    <section><h2>6. Matching and recommendations</h2><p>The network can compare profile skills, profession, interests, industry, availability, location preferences, shared projects, role requirements and network paths to suggest people, projects or introductions that may be useful. Activity is used for matching only where your settings permit it.</p><p>Recommendations are relevance signals, not decisions about employment, credit, eligibility or personal worth. They do not guarantee identity, qualifications, suitability or an outcome. Important project and membership decisions remain with people, and we aim to show understandable reasons for a recommendation where practical.</p><p>We do not intend to make solely automated decisions that produce legal or similarly significant effects. If that changes, we will provide appropriate information and safeguards before the new use begins.</p></section>

    <section><h2>7. Visibility and member choices</h2><p>Your profile, project and post audiences are controlled by the visibility options available when you publish or in Settings. You may be able to control profile visibility, location display, availability, follower and following lists, messaging permissions, introductions, notifications and activity-based matching.</p><p>Project owners and team members can see information needed to assess applications and coordinate shared work. People invited to a message or meeting can see the identity and content shared within that conversation. Public content may be indexed, linked to or viewed without an account.</p><p>Changing a visibility setting affects future access through the service. It may not remove copies already saved by another person, included in an email, preserved for a safety case or retained where law requires us to keep a record.</p></section>

    <section><h2>8. Sharing and service providers</h2><p>We share information with suppliers that provide hosting, databases, authentication, email delivery, security, analytics, file storage, calendar or meeting functionality, and technical support. They may process information only for the agreed service and subject to appropriate contractual and security obligations.</p><p>We may share information with another organisation where you ask us to, where a project or integration requires it, during a genuine corporate transaction, or where reasonably necessary to comply with law, enforce our terms, protect legal rights, or respond to a serious safety or security risk.</p><p>We do not sell personal information. If information is transferred internationally, we use an available legal mechanism and proportionate safeguards for the destination and type of information.</p></section>

    <section><h2>9. Safety, reports and legal requests</h2><p>Reports may include the reporting member’s account details, the reason for the report, relevant content, contextual records and actions taken. Access is restricted to people who need the information for review, safeguarding, appeal, legal compliance or service security.</p><p>We may preserve a limited evidence snapshot after content is edited or removed when it is reasonably required for an active report, appeal, legal hold, fraud investigation or serious safety concern. We do not use private communications for advertising.</p></section>

    <section id="cookies"><h2>10. Cookies and local storage</h2><p>Essential cookies or local storage support sign-in, security, accessibility preferences and the storage of your cookie choice. These are required for requested features to work and cannot always be disabled through the service.</p><p>Optional analytics help us understand broad product usage and reliability. Analytics are off unless you select “Allow analytics” in the cookie banner. Authentication, verification and password-reset paths are excluded from analytics collection, and query strings are removed from recorded page addresses.</p><p>You can clear this site’s cookies and local storage in your browser to reset your choice. The banner will ask again on a later visit. Browser controls may also block storage, although some features may then work less reliably.</p></section>

    <section><h2>11. Retention and deletion</h2><p>You can request account deletion from Settings under Security and password. We first deactivate the account, revoke sign-in, disconnect integrations, label the profile and shared content as inactive, cancel future meets you host, and begin any project leadership handover required by the project rules.</p><p>You have 30 days to recover the account using its previous email address and password. After that recovery window, we permanently anonymise the personal account details. Completed project ownership transfers and cancelled meets are not automatically reversed if you recover.</p><p>We keep account and service information while your account is active and for a reasonable period afterwards where needed to close the account, maintain security, meet legal obligations, resolve disputes or prevent repeat abuse. Different records have different retention needs.</p><p>Public or shared content may be removed or de-identified following account closure unless continued retention is justified. Messages already shared with other members, security logs, moderation evidence, transaction records, backups and audit trails may be kept for longer where necessary. Backups are protected and expire through managed rotation rather than being edited immediately.</p></section>

    <section><h2>12. Security</h2><p>We use measures designed to protect information, including access controls, password hashing, encrypted supported integration tokens, restricted administrative permissions, audit records, rate limits and secure transport. Access to sensitive operational data is limited according to role and purpose.</p><p>No online service can guarantee absolute security. Keep your password private, use a unique password, review unexpected account activity and report suspected compromise promptly through Help.</p></section>

    <section><h2>13. Your data rights</h2><p>Depending on the law that applies to you and the reason we use the information, you may have rights to be informed; access your information; correct inaccurate information; request deletion; restrict or object to processing; receive certain information in a portable format; withdraw consent; and challenge certain automated decisions.</p><p>Use the in-product Help area to make a request. Tell us which account and information the request concerns. We may verify your identity, ask for clarification and retain a record of the request. Some rights are subject to legal limits and may not apply to every record.</p><p>You may complain to the data-protection regulator where you live. In the United Kingdom, this is the Information Commissioner’s Office. We would appreciate the opportunity to address your concern first, but you do not have to contact us before contacting a regulator.</p></section>

    <section><h2>14. Younger members</h2><p>The service is not intended for a child who cannot lawfully consent to its use or enter these terms. Where younger members are permitted, we may apply stricter visibility, contact, matching and safety controls. Do not attempt to bypass age-related safeguards.</p><p>If you believe a child has provided information without the necessary permission or is at risk on the service, report it through the available safety or Help controls.</p></section>

    <section><h2>15. Changes to this notice</h2><p>We may update this notice when the product, suppliers, law or our practices change. The effective date at the top shows the current version. If a change materially affects how information is used or the choices available to you, we will provide additional notice where reasonably possible.</p></section>
  </LegalPage>;
}
