import type { Metadata } from "next";
import { LegalPage } from "@/components/public-site-shell";

export const metadata: Metadata = { title: "Privacy — nice 2 network", description: "How nice 2 network handles personal information and privacy choices." };

export default function PrivacyPage() {
  return <LegalPage eyebrow="PRIVACY / YOUR CHOICES" title="Privacy, in plain language." summary="We use information to run the network, make relevant connections and keep people safe. Your visibility and matching choices remain under your control.">
    <section><h2>1. What we collect</h2><p>We collect the information you provide when you create an account or profile, including your name, contact details, skills, interests, location preferences, availability and career information. We also store projects, posts, messages, meeting details, applications, reactions and reports you create in the service.</p><p>Technical records may include device and browser information, security events, approximate network information and product activity. Connected calendar services provide only the information needed to create or manage meetings you request.</p></section>
    <section><h2>2. Why we use it</h2><p>We use personal information to provide the service, authenticate accounts, show profiles and projects according to their visibility, recommend relevant people or roles, deliver communications, prevent misuse, investigate reports and improve reliability.</p><p>Matching can consider profile skills, interests, industry, location preferences, availability, shared projects and network paths. Recommendations are aids, not decisions about employment or eligibility, and the product explains key reasons where practical.</p></section>
    <section><h2>3. What other people see</h2><p>Your profile and content are shown according to the audience you select. You can change profile visibility, location display, availability, follower lists, messaging permissions, introduction preferences and activity-based matching in Settings.</p><p>Project owners may see applications and information you choose to share with them. Private message bodies are not available to ordinary administrators; reported material may be accessed by authorised reviewers when needed to investigate a case.</p></section>
    <section><h2>4. Sharing and service providers</h2><p>We share information with suppliers that host, secure, analyse or deliver the service only as needed for those functions. If you connect Google or Microsoft services, their use is also governed by your settings and their terms. We may disclose information where law requires it or where necessary to protect people, the service or legal rights.</p><p>nice 2 network was built by IntAillium. We do not sell personal information.</p></section>
    <section id="cookies"><h2>5. Cookies and local storage</h2><p>Essential storage keeps your session, security and accessibility or cookie choices working. Optional analytics measure broad product usage without including authentication, verification or password-reset paths. Analytics remain off unless you select “Allow analytics” in the cookie banner.</p><p>You can clear site data in your browser to reset your choice. On your next visit, the banner will ask again.</p></section>
    <section><h2>6. Retention and security</h2><p>We keep information for as long as needed to provide the service, meet legal obligations, resolve disputes and protect the community. Retention periods vary by record type. We use access controls, encryption for supported integration tokens, audit records and other safeguards, but no online service can promise absolute security.</p></section>
    <section><h2>7. Your rights</h2><p>Depending on where you live, you may have rights to access, correct, delete, restrict or object to use of your information, receive a portable copy, or complain to a data-protection authority. Use the in-product Help area to make a privacy request. We may need to verify your identity first.</p></section>
    <section><h2>8. Changes</h2><p>We may update this notice as the product or law changes. We will post the new date here and give additional notice when a change materially affects your choices.</p></section>
  </LegalPage>;
}
