import type { Metadata } from "next";
import { LegalPage } from "@/components/public-site-shell";

export const metadata: Metadata = { title: "Terms & Conditions — nice 2 network", description: "The terms for using nice 2 network." };

export default function TermsPage() {
  return <LegalPage eyebrow="TERMS / THE AGREEMENT" title="Clear terms for useful work." summary="These terms set the ground rules for using nice 2 network. By creating an account or using the service, you agree to them.">
    <section><h2>1. Using the service</h2><p>You must provide accurate account information, protect your sign-in credentials and use the service lawfully. You are responsible for activity under your account and should tell us promptly if you believe it has been compromised.</p><p>You may not scrape the service, bypass access controls, interfere with its operation, introduce malicious code, impersonate another person or use information from the network for unsolicited marketing.</p></section>
    <section><h2>2. Age and authority</h2><p>You must meet the minimum age required to use online services where you live. If you use nice 2 network for an organisation, you confirm that you are authorised to agree to these terms for it. Additional safeguards may apply to younger members.</p></section>
    <section><h2>3. Your content and projects</h2><p>You keep ownership of content you create. You give us a worldwide, non-exclusive licence to host, reproduce, adapt and display it only as needed to operate, secure and promote the service in line with your visibility choices. You confirm that you have the rights needed to share it.</p><p>Project members are responsible for agreeing ownership, confidentiality, payment and other working terms between themselves. nice 2 network helps people discover and communicate; it is not automatically a party to those agreements.</p></section>
    <section><h2>4. Community and moderation</h2><p>You must follow the Community Code. We may remove content, restrict features, suspend or close accounts, preserve relevant evidence, or contact authorities where reasonably necessary for safety, security, legal compliance or service integrity. Where available, you may appeal a moderation decision.</p></section>
    <section><h2>5. Recommendations and opportunities</h2><p>Matches, role suggestions, network paths and other recommendations are informational. They do not guarantee suitability, identity, qualifications, funding, employment or project outcomes. Check people and opportunities for yourself before making commitments or sharing sensitive information.</p></section>
    <section><h2>6. Third-party services</h2><p>The service may link to or connect with third-party products such as calendar, meeting or external websites. Those services have their own terms and privacy practices, and we are not responsible for their independent operation.</p></section>
    <section><h2>7. Availability and liability</h2><p>We aim to keep nice 2 network dependable, but it is provided on an “as available” basis and may change, pause or contain errors. Nothing in these terms excludes liability that cannot legally be excluded. To the extent permitted by law, we are not liable for indirect loss, lost opportunities, or arrangements made between members.</p></section>
    <section><h2>8. Ending access and changes</h2><p>You may stop using the service at any time. We may end or limit access where these terms are breached, risk is created or the service is discontinued. Provisions that by their nature should continue—including ownership, licences, liability and dispute terms—will survive.</p><p>We may update these terms. Material changes will be communicated reasonably, and continued use after they take effect means you accept the revised terms.</p></section>
    <section><h2>9. Questions</h2><p>Use the in-product Help area for questions, legal notices or concerns about these terms. nice 2 network was built by IntAillium.</p></section>
  </LegalPage>;
}
