import type { Metadata } from "next";
import { LegalPage } from "@/components/public-site-shell";

export const metadata: Metadata = {
  title: "Terms — nice 2 network",
  description: "The terms that apply when you access or use nice 2 network.",
};

export default function TermsPage() {
  return <LegalPage eyebrow="TERMS / THE AGREEMENT" title="Clear terms for useful work." summary="These Terms explain the agreement between you and nice 2 network, the standards that protect the community, and the responsibilities that remain with members when they work together.">
    <section><h2>1. Accepting these Terms</h2><p>These Terms apply when you visit, create an account or use nice 2 network. By using the service, you agree to these Terms, the Privacy notice and the Community Code. If you do not agree, do not use the service.</p><p>If you use the network on behalf of a company, charity, school or other organisation, you confirm that you have authority to agree to these Terms for that organisation. “You” then includes both you and that organisation where the context requires it.</p></section>

    <section><h2>2. Eligibility and age</h2><p>You must be legally able to enter this agreement and meet the minimum age required for an online service where you live. Do not create an account for another person without authority or misrepresent your age, identity, affiliation or professional status.</p><p>Additional visibility, contact and safety restrictions may apply to younger members. You must not bypass, encourage someone else to bypass, or interfere with those safeguards.</p></section>

    <section><h2>3. Your account</h2><p>Provide accurate registration information, keep it reasonably current and protect your credentials. Use a strong, unique password and do not share access or allow another person to act through your account. You are responsible for activity carried out through your account unless caused by our failure to apply reasonable security.</p><p>Tell us promptly through Help if you suspect unauthorised access, impersonation or loss of control. We may require verification, close active sessions or temporarily restrict an account while investigating a security concern.</p></section>

    <section><h2>4. Acceptable use</h2><p>Use the network lawfully, honestly and in accordance with the Community Code. Do not harass, threaten, exploit or discriminate against people; share illegal or harmful content; expose private information; impersonate others; manipulate recommendations; send repeated unwanted contact; or promote deceptive opportunities.</p><p>You must not probe or bypass security, scrape the service without written permission, introduce malicious code, overload infrastructure, reverse engineer protected parts of the service, automate account activity in a misleading way, or use network information to build unsolicited marketing lists.</p><p>Do not use the service to facilitate exploitation, fraud, unsafe work, unlawful discrimination, infringement, or activity that places a child or vulnerable person at risk.</p></section>

    <section><h2>5. Your content</h2><p>You keep ownership of original content you submit. You give us a worldwide, non-exclusive, royalty-free licence to host, copy, format, adapt, transmit and display that content only as reasonably needed to operate, secure, improve and explain the service in line with your visibility choices. This licence ends when the content is deleted, subject to reasonable backups, existing shares and records we must retain.</p><p>You confirm that you have the rights and permissions needed to submit the content and grant this licence. Do not upload confidential material, personal data, copyrighted work or another person’s likeness unless you are authorised to do so.</p><p>Feedback and product suggestions may be used to improve the service without payment or obligation, but we will not treat a confidential business idea as general feedback merely because it was shared through a private project or support conversation.</p></section>

    <section><h2>6. Projects and working relationships</h2><p>nice 2 network helps people discover projects, roles and collaborators. Unless we expressly agree otherwise in writing, we are not the employer, recruiter, agent, partner, client, contractor or representative of a member or project.</p><p>Members are responsible for agreeing the scope of work, decision-making, confidentiality, intellectual-property ownership, expenses, payment, tax, employment status, safeguarding and exit arrangements that apply to their project. Put important terms in writing before substantial work begins.</p><p>We do not guarantee that a project is viable, funded, lawful or safe, or that a member has the identity, experience, authority or resources they claim. Carry out proportionate checks before sharing sensitive information, transferring money or committing significant time.</p></section>

    <section><h2>7. Applications, introductions and recommendations</h2><p>Matches, suggested roles, project scores, network paths and introductions are informational tools based on available profile and service information. They may be incomplete, delayed or wrong and do not amount to professional advice, endorsement or a guarantee of suitability.</p><p>Project owners remain responsible for fair and lawful selection decisions. Members must not use protected characteristics or information obtained through the network to discriminate unlawfully. No recommendation guarantees employment, investment, funding, compensation or project success.</p></section>

    <section><h2>8. Messages and meetings</h2><p>Messaging and meeting tools are provided for legitimate network and project communication. Respect contact preferences, obtain permission before recording, and make participants aware when a meeting or conversation will be shared, transcribed or used as a podcast.</p><p>Do not use private communications to threaten, pressure, deceive or repeatedly contact another person after they have asked you to stop. We may restrict messaging or meeting access where settings, safety rules or account status require it.</p></section>

    <section><h2>9. Connected and third-party services</h2><p>You may choose to connect calendar, meeting, authentication or other third-party services. Your use of those services is also governed by their own terms and privacy practices. You authorise us to exchange the information required to perform the action you requested.</p><p>Links and previews do not mean we endorse the external site, person or content. We are not responsible for a third party’s availability, security, accuracy or independent actions. Disconnect an integration if you no longer want the network to use it.</p></section>

    <section><h2>10. Community safety and moderation</h2><p>We may investigate reports and take proportionate action to protect members, comply with law or enforce these Terms and the Community Code. Action may include reducing visibility, removing content, limiting contact, preserving evidence, restricting features, suspending or closing an account, or referring a serious matter to an appropriate authority.</p><p>We consider context, severity, risk, history and available evidence. Not every report results in action, and we may be unable to disclose confidential details about another member. Where an appeal route is available, follow the instructions in the decision notice and provide relevant information honestly.</p><p>We may act without advance notice where delay could increase risk, compromise an investigation, threaten service security or prevent compliance with law.</p></section>

    <section><h2>11. Our intellectual property</h2><p>The service, brand, interface, software, databases, designs and documentation—excluding member content—belong to us or our licensors. These Terms give you a limited, personal, revocable, non-transferable right to use the service for its intended purpose.</p><p>Do not copy our branding, create a confusingly similar service, remove ownership notices or use our software or content beyond what normal use of the network allows without written permission.</p></section>

    <section><h2>12. Service changes and availability</h2><p>We aim to provide a dependable service, but features may change, pause, fail or be discontinued. We may release preview or experimental features that are incomplete and may change without notice. We do not promise uninterrupted access, permanent storage or compatibility with every device or external service.</p><p>We may carry out maintenance, apply limits or change technical requirements to protect security, improve performance or keep the service sustainable. Where practical, we will give reasonable notice of a material discontinuation that affects stored member content.</p></section>

    <section><h2>13. Ending or restricting access</h2><p>You may stop using the service at any time and may request account closure through the available account or Help controls. Before leaving, save information you are entitled to keep and make appropriate arrangements with active project collaborators.</p><p>We may restrict or end access if you breach these Terms, create material risk, repeatedly violate community standards, fail required verification, misuse the service, or where continued access would be unlawful or technically impractical. We will provide notice and reasons where reasonably possible and safe to do so.</p></section>

    <section><h2>14. Disclaimers</h2><p>nice 2 network is a collaboration platform, not a provider of legal, financial, employment, safeguarding or investment advice. Information supplied by members belongs to those members and may not be verified. You are responsible for evaluating information and obtaining professional advice where appropriate.</p><p>The service is provided on an “as available” basis. To the extent permitted by law, we do not give implied guarantees about uninterrupted availability, fitness for a particular project, member conduct or the outcome of an introduction. Nothing in these Terms affects mandatory rights that cannot lawfully be excluded.</p></section>

    <section><h2>15. Responsibility and liability</h2><p>Each party remains responsible for loss it causes through breach of these Terms, negligence or unlawful conduct. Nothing excludes or limits liability for death or personal injury caused by negligence, fraud, fraudulent misrepresentation, or any liability that law does not allow to be limited.</p><p>To the extent permitted by law, we are not responsible for indirect or unforeseeable loss, lost opportunities, loss arising from arrangements between members, or damage caused by external services or content outside our reasonable control. If you use the service as a consumer, your statutory consumer rights remain unaffected.</p></section>

    <section><h2>16. Governing law and disputes</h2><p>Please contact us through Help first so we can try to resolve a concern informally. If you are a consumer, you keep any mandatory rights to bring a claim in the courts available under the law where you live.</p><p>For members using the service wholly for business purposes, these Terms are governed by the law of England and Wales and the courts of England and Wales will have jurisdiction, unless another arrangement is required by law.</p></section>

    <section><h2>17. Changes and general terms</h2><p>We may update these Terms when the service, law or risk environment changes. The effective date at the top identifies the current version. We will provide additional notice of material changes where reasonably possible. Continued use after an updated version takes effect means you accept it.</p><p>If a court finds one provision unenforceable, the remaining provisions continue. A delay in enforcing a provision is not a waiver. You may not transfer this agreement without our consent; we may transfer it as part of a reorganisation, financing or transfer of the service, subject to applicable law.</p></section>

    <section><h2>18. Contact</h2><p>Use the in-product Help area for questions, legal notices, account concerns or complaints about these Terms. nice 2 network was founded by Phillip Joseph, Nathan Baiden and Nicholas Wright and built in partnership with IntAillium.</p></section>
  </LegalPage>;
}
