export type CareerSector = {
  sector: string;
  careers: readonly string[];
  keywords?: readonly string[];
};

/**
 * Broad, user-facing career families rather than a formal occupational coding
 * system. Roles are intentionally recognisable across seniority levels and UK
 * and international job markets so they work well as search terms.
 */
export const CAREER_SECTORS: readonly CareerSector[] = [
  { sector: "Agriculture, food & land", keywords: ["farming", "forestry", "fisheries"], careers: ["Agricultural engineer", "Agronomist", "Animal care worker", "Chef", "Farm manager", "Food scientist", "Forester", "Horticulturist", "Nutritionist", "Quality assurance technician", "Supply chain manager", "Veterinary surgeon"] },
  { sector: "Arts, culture & heritage", keywords: ["museum", "gallery", "library"], careers: ["Actor", "Archivist", "Arts administrator", "Choreographer", "Conservator", "Curator", "Dancer", "Historian", "Librarian", "Museum educator", "Musician", "Theatre director"] },
  { sector: "Automotive & mobility", keywords: ["vehicles", "electric vehicles", "motorsport"], careers: ["Automotive engineer", "Automotive technician", "Battery engineer", "Driving instructor", "Fleet manager", "Mechanic", "Mobility planner", "Motorsport engineer", "Vehicle designer", "Vehicle safety engineer"] },
  { sector: "Business, consulting & administration", keywords: ["management", "office", "strategy"], careers: ["Account manager", "Administrative assistant", "Business analyst", "Business development manager", "Chief executive", "Consultant", "Customer success manager", "Executive assistant", "Management consultant", "Office manager", "Operations manager", "Project manager", "Receptionist", "Strategy manager"] },
  { sector: "Charity, community & social impact", keywords: ["nonprofit", "ngo", "voluntary", "community"], careers: ["Campaign manager", "Charity director", "Community development worker", "Community organiser", "Corporate social responsibility manager", "Fundraising manager", "Grant writer", "International development adviser", "Outreach worker", "Policy advocate", "Programme officer", "Social enterprise founder", "Volunteer coordinator"] },
  { sector: "Climate, energy & utilities", keywords: ["renewables", "electricity", "water", "net zero"], careers: ["Climate scientist", "Energy analyst", "Energy engineer", "Environmental consultant", "Grid engineer", "Hydrologist", "Renewable energy technician", "Solar engineer", "Sustainability manager", "Utilities engineer", "Wastewater engineer", "Wind turbine technician"] },
  { sector: "Construction & built environment", keywords: ["building", "infrastructure", "trades"], careers: ["Architect", "Bricklayer", "Building services engineer", "Carpenter", "Civil engineer", "Construction manager", "Electrician", "Interior architect", "Landscape architect", "Planner", "Plumber", "Quantity surveyor", "Structural engineer", "Surveyor"] },
  { sector: "Consumer products & retail", keywords: ["shops", "ecommerce", "merchandising"], careers: ["Buyer", "Category manager", "Customer service adviser", "E-commerce manager", "Merchandiser", "Product developer", "Retail manager", "Sales assistant", "Store manager", "Visual merchandiser", "Wholesale manager"] },
  { sector: "Creative, design & crafts", keywords: ["visual", "product design", "craft"], careers: ["Animator", "Art director", "Ceramicist", "Fashion designer", "Graphic designer", "Illustrator", "Industrial designer", "Interior designer", "Jewellery designer", "Photographer", "Product designer", "Textile designer", "UX designer", "Videographer"] },
  { sector: "Education & training", keywords: ["schools", "learning", "teaching"], careers: ["Academic researcher", "Careers adviser", "Early years practitioner", "Education administrator", "Education psychologist", "Headteacher", "Learning designer", "Lecturer", "Primary school teacher", "Secondary school teacher", "Special educational needs coordinator", "Teacher", "Teaching assistant", "Training manager", "Tutor"] },
  { sector: "Engineering & manufacturing", keywords: ["factory", "production", "industrial"], careers: ["Aerospace engineer", "Chemical engineer", "Design engineer", "Electrical engineer", "Engineering technician", "Industrial engineer", "Maintenance engineer", "Manufacturing engineer", "Materials engineer", "Mechanical engineer", "Production manager", "Quality engineer", "Robotics engineer", "Welder"] },
  { sector: "Entertainment, media & publishing", keywords: ["film", "television", "radio", "books"], careers: ["Author", "Broadcast journalist", "Content producer", "Copy editor", "Editor", "Film director", "Journalist", "Location manager", "Podcast producer", "Presenter", "Production coordinator", "Publisher", "Radio producer", "Screenwriter", "Sound engineer"] },
  { sector: "Finance, banking & insurance", keywords: ["fintech", "accounting", "investment"], careers: ["Accountant", "Actuary", "Auditor", "Bank manager", "Bookkeeper", "Compliance analyst", "Credit analyst", "Financial adviser", "Financial analyst", "Insurance broker", "Investment analyst", "Mortgage adviser", "Risk manager", "Tax adviser", "Trader"] },
  { sector: "Government & public services", keywords: ["civil service", "council", "public sector"], careers: ["Civil servant", "Diplomat", "Economist", "Electoral services officer", "Intelligence analyst", "Local government officer", "Member of parliament", "Policy adviser", "Public affairs manager", "Public health officer", "Registrar", "Statistician", "Trade officer"] },
  { sector: "Healthcare & clinical care", keywords: ["medical", "hospital", "health"], careers: ["Anaesthetist", "Care worker", "Dentist", "Dietitian", "Doctor", "Healthcare assistant", "Midwife", "Nurse", "Occupational therapist", "Optometrist", "Paramedic", "Pharmacist", "Physiotherapist", "Psychologist", "Radiographer", "Speech and language therapist", "Surgeon"] },
  { sector: "Hospitality, tourism & events", keywords: ["hotel", "travel", "catering"], careers: ["Bar manager", "Barista", "Catering manager", "Concierge", "Event manager", "Flight attendant", "Hotel manager", "Restaurant manager", "Sommelier", "Tour guide", "Tourism manager", "Travel agent", "Wedding planner"] },
  { sector: "Legal, justice & compliance", keywords: ["law", "courts", "regulation"], careers: ["Barrister", "Compliance officer", "Coroner", "Court clerk", "Criminologist", "Forensic scientist", "Judge", "Legal executive", "Mediator", "Paralegal", "Probation officer", "Solicitor", "Trademark attorney"] },
  { sector: "Life sciences, biotech & pharmaceuticals", keywords: ["laboratory", "medicine", "biotech"], careers: ["Biomedical scientist", "Biotechnologist", "Clinical research associate", "Epidemiologist", "Geneticist", "Laboratory technician", "Medical science liaison", "Microbiologist", "Pharmacologist", "Regulatory affairs specialist", "Research scientist", "Toxicologist"] },
  { sector: "Marketing, communications & sales", keywords: ["advertising", "public relations", "growth"], careers: ["Advertising account executive", "Brand manager", "Communications manager", "Content strategist", "Copywriter", "Digital marketer", "Market researcher", "Marketing manager", "Partnerships manager", "Public relations officer", "Sales manager", "SEO specialist", "Social media manager"] },
  { sector: "Property, real estate & facilities", keywords: ["housing", "estate agency", "facilities"], careers: ["Building manager", "Estate agent", "Facilities manager", "Housing officer", "Lettings agent", "Property developer", "Property manager", "Real estate analyst", "Valuer"] },
  { sector: "Science & research", keywords: ["academic", "laboratory", "discovery"], careers: ["Astronomer", "Chemist", "Data scientist", "Ecologist", "Geologist", "Marine biologist", "Mathematician", "Meteorologist", "Oceanographer", "Physicist", "Research assistant", "Social researcher"] },
  { sector: "Security, defence & emergency services", keywords: ["armed forces", "police", "fire"], careers: ["Army officer", "Cyber security analyst", "Emergency planner", "Firefighter", "Forensic investigator", "Intelligence officer", "Police officer", "Royal Air Force officer", "Royal Navy officer", "Security manager"] },
  { sector: "Sport, fitness & wellbeing", keywords: ["exercise", "coaching", "leisure"], careers: ["Athlete", "Fitness instructor", "Leisure centre manager", "Personal trainer", "Pilates instructor", "Sports coach", "Sports development officer", "Sports psychologist", "Sports therapist", "Strength and conditioning coach", "Yoga teacher"] },
  { sector: "Technology, data & digital", keywords: ["software", "IT", "internet", "artificial intelligence"], careers: ["AI engineer", "Cloud engineer", "Computer support specialist", "Cyber security analyst", "Data analyst", "Data engineer", "Data scientist", "Database administrator", "DevOps engineer", "Game developer", "IT project manager", "Machine learning engineer", "Network engineer", "Product manager", "QA engineer", "Software engineer", "Solutions architect", "Systems analyst", "UX researcher", "Web developer"] },
  { sector: "Telecommunications", keywords: ["mobile", "broadband", "networks"], careers: ["Broadcast engineer", "Fibre engineer", "Network planner", "Radio frequency engineer", "Satellite engineer", "Telecommunications engineer", "Telecommunications technician"] },
  { sector: "Transport, logistics & supply chain", keywords: ["shipping", "rail", "aviation", "delivery"], careers: ["Air traffic controller", "Airline pilot", "Courier", "Freight forwarder", "Logistics manager", "Procurement manager", "Railway engineer", "Ship officer", "Supply chain analyst", "Train driver", "Transport planner", "Warehouse manager"] },
  { sector: "Beauty, fashion & personal care", keywords: ["cosmetics", "hair", "styling"], careers: ["Barber", "Beauty therapist", "Costume designer", "Fashion buyer", "Fashion stylist", "Hairdresser", "Make-up artist", "Nail technician", "Spa manager"] },
  { sector: "Other", keywords: ["cross-sector", "multidisciplinary"], careers: ["Apprentice", "Entrepreneur", "Freelancer", "Intern", "Portfolio professional", "Self-employed professional"] },
] as const;

export const PROJECT_INDUSTRIES = CAREER_SECTORS.map(({ sector }) => sector);
