import "server-only";
import { and, eq, inArray, ne, or, sql } from "drizzle-orm";
import { getDb } from "@/db";
import { blocks, follows, memberRecommendations, privacySettings, projectMembers, projectRoles, projects, users } from "@/db/schema";

const norm=(value:string|null|undefined)=>(value??"").trim().toLowerCase();
const words=(values:Array<string|null|undefined>)=>new Set(values.flatMap(value=>norm(value).split(/[^a-z0-9+#.]+/).filter(part=>part.length>1)));
const overlap=(a:Set<string>,b:Set<string>)=>[...a].filter(value=>b.has(value));
const sameZone=(a:string,b:string)=>a===b?1:a.split("/")[0]===b.split("/")[0]?0.5:0;

export type PeopleSuggestion={recommendationId:string;id:string;name:string|null;image:string|null;profession:string|null;location:string|null;score:number;reasons:string[];isFollowing:boolean;isMutual:boolean};

export async function recommendPeople(userId:string,limit=20):Promise<PeopleSuggestion[]> {
  const db=getDb(),[viewer]=await db.select().from(users).where(eq(users.id,userId)).limit(1);if(!viewer)return[];
  const [following,blocked,memberProjects,ownedRoles,hidden]=await Promise.all([
    db.select({id:follows.followingId}).from(follows).where(eq(follows.followerId,userId)),
    db.select({blockerId:blocks.blockerId,blockedId:blocks.blockedId}).from(blocks).where(or(eq(blocks.blockerId,userId),eq(blocks.blockedId,userId))),
    db.select({projectId:projectMembers.projectId}).from(projectMembers).where(eq(projectMembers.userId,userId)),
    db.select({title:projectRoles.title,department:projectRoles.department,requiredSkills:projectRoles.requiredSkills,usefulSkills:projectRoles.usefulSkills}).from(projectRoles).innerJoin(projects,eq(projects.id,projectRoles.projectId)).where(and(eq(projects.ownerId,userId),eq(projectRoles.status,"open"))),
    db.select({id:memberRecommendations.suggestedUserId}).from(memberRecommendations).where(and(eq(memberRecommendations.userId,userId),inArray(memberRecommendations.status,["hidden","not_relevant"]))),
  ]);
  const excluded=new Set([userId,...following.map(row=>row.id),...hidden.map(row=>row.id),...blocked.flatMap(row=>[row.blockerId,row.blockedId])]);
  const ageBands=viewer.ageBand==="teen_16_17"?["teen_16_17"]:["adult","adult_18_24","adult_25_plus"];
  const candidates=await db.select({id:users.id,name:users.name,image:users.image,profession:users.profession,industry:users.industry,primarySkill:users.primarySkill,secondarySkill:users.secondarySkill,tertiarySkill:users.tertiarySkill,interests:users.interests,location:users.location,city:users.city,country:users.country,timezone:users.timezone,availability:users.availability,workMode:users.workMode,showLocation:privacySettings.showLocation,showAvailability:privacySettings.showAvailability}).from(users).leftJoin(privacySettings,eq(privacySettings.userId,users.id)).where(and(ne(users.id,userId),eq(users.status,"active"),sql`${users.emailVerified} is not null`,sql`${users.onboardingCompletedAt} is not null`,inArray(users.ageBand,ageBands),or(eq(privacySettings.profileVisibility,"network"),eq(privacySettings.profileVisibility,"public"),sql`${privacySettings.userId} is null`),sql`not exists (select 1 from sanctions s where s.user_id=${users.id} and s.status='active' and (s.expires_at is null or s.expires_at>now()))`)).limit(250);
  const candidateIds=candidates.map(row=>row.id),sharedRows=candidateIds.length&&memberProjects.length?await db.select({userId:projectMembers.userId,projectId:projectMembers.projectId}).from(projectMembers).where(and(inArray(projectMembers.userId,candidateIds),inArray(projectMembers.projectId,memberProjects.map(row=>row.projectId)))):[];
  const mutualRows=candidateIds.length&&following.length?await db.select({followerId:follows.followerId,followingId:follows.followingId}).from(follows).where(and(inArray(follows.followerId,following.map(row=>row.id)),inArray(follows.followingId,candidateIds))):[];
  const reciprocal=candidateIds.length?new Set((await db.select({id:follows.followerId}).from(follows).where(and(eq(follows.followingId,userId),inArray(follows.followerId,candidateIds)))).map(row=>row.id)):new Set<string>();
  const viewerSkills=[viewer.primarySkill,viewer.secondarySkill,viewer.tertiarySkill],viewerTerms=words([viewer.profession,viewer.industry,...viewerSkills]),viewerInterests=new Set(viewer.interests.map(norm)),roleTerms=words(ownedRoles.flatMap(role=>[role.title,role.department,...role.requiredSkills,...role.usefulSkills]));
  const scored=candidates.filter(candidate=>!excluded.has(candidate.id)).map(candidate=>{
    const ranked=[candidate.primarySkill,candidate.secondarySkill,candidate.tertiarySkill],candidateTerms=words([candidate.profession,candidate.industry,...ranked]),sharedTerms=overlap(viewerTerms,candidateTerms),sharedInterests=overlap(viewerInterests,new Set(candidate.interests.map(norm))),roleHits=ranked.map((skill,index)=>roleTerms.has(norm(skill))?[1,.75,.55][index]:0).reduce((a,b)=>a+b,0),sharedProjects=new Set(sharedRows.filter(row=>row.userId===candidate.id).map(row=>row.projectId)).size,mutualPaths=new Set(mutualRows.filter(row=>row.followingId===candidate.id).map(row=>row.followerId)).size;
    const projectFit=Math.min(40,roleHits*20),professional=Math.min(20,sharedTerms.length*5),relationship=Math.min(15,sharedProjects*8+mutualPaths*3),relevance=Math.min(10,sharedInterests.length*3+(norm(viewer.industry)===norm(candidate.industry)?4:0)),location=Math.min(10,(viewer.city&&candidate.city&&norm(viewer.city)===norm(candidate.city)?7:0)+(sameZone(viewer.timezone,candidate.timezone)*3)),availability=candidate.showAvailability!==false&&candidate.availability==="open"?5:2,score=Math.round(projectFit+professional+relationship+relevance+location+availability);
    const reasons=[...(roleHits>0?[`Your project needs ${ranked.find(skill=>roleTerms.has(norm(skill)))}`]:[]),...(sharedProjects?[`${sharedProjects} mutual ${sharedProjects===1?"project":"projects"}`]:[]),...(mutualPaths?[`${mutualPaths} useful network ${mutualPaths===1?"path":"paths"}`]:[]),...(sharedInterests.length?[`${sharedInterests.length} shared ${sharedInterests.length===1?"interest":"interests"}`]:[]),...(viewer.city&&candidate.city&&norm(viewer.city)===norm(candidate.city)?["Near you"]:[]),...(sharedTerms.length?[`Shared ${sharedTerms[0]} experience`]:[])].slice(0,3);
    return{candidate,score,components:{projectFit,professional,relationship,relevance,location,availability},reasons:reasons.length?reasons:["Complementary professional experience"]};
  }).filter(row=>row.score>0).sort((a,b)=>b.score-a.score||a.candidate.id.localeCompare(b.candidate.id)).slice(0,Math.min(50,limit));
  const output:PeopleSuggestion[]=[];for(const row of scored){const [record]=await db.insert(memberRecommendations).values({userId,suggestedUserId:row.candidate.id,score:row.score,componentScores:row.components,reasons:row.reasons,expiresAt:new Date(Date.now()+7*86400000)}).onConflictDoUpdate({target:[memberRecommendations.userId,memberRecommendations.suggestedUserId,memberRecommendations.algorithmVersion],set:{score:row.score,componentScores:row.components,reasons:row.reasons,status:"active",generatedAt:new Date(),expiresAt:new Date(Date.now()+7*86400000)}}).returning({id:memberRecommendations.id});output.push({recommendationId:record.id,id:row.candidate.id,name:row.candidate.name,image:row.candidate.image,profession:row.candidate.profession,location:row.candidate.showLocation===false?null:row.candidate.location,score:row.score,reasons:row.reasons,isFollowing:false,isMutual:reciprocal.has(row.candidate.id)})}return output;
}
