import { and, count, desc, eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { getDb } from "@/db";
import { adminAssignments, users } from "@/db/schema";
import { adminRoles, requirePermission } from "@/lib/admin";
import { ApiError, apiError } from "@/lib/api";
import { audit } from "@/lib/audit";
const schema=z.object({userId:z.uuid(),role:z.enum(adminRoles),status:z.enum(["active","suspended","revoked"]),reason:z.string().trim().min(10).max(1000)});
export async function GET(){try{const admin=await requirePermission("admins.manage");const rows=await getDb().select({id:adminAssignments.id,userId:adminAssignments.userId,name:users.name,email:users.email,image:users.image,role:adminAssignments.role,status:adminAssignments.status,expiresAt:adminAssignments.expiresAt,updatedAt:adminAssignments.updatedAt}).from(adminAssignments).innerJoin(users,eq(users.id,adminAssignments.userId)).orderBy(desc(adminAssignments.updatedAt));await audit(admin.user.id,"admin.assignments_viewed","admin_assignment",undefined,{count:rows.length},{permission:"admins.manage",severity:"high"});return NextResponse.json({administrators:rows})}catch(error){return apiError(error)}}
export async function POST(request:Request){try{const admin=await requirePermission("admins.manage");const input=schema.parse(await request.json());const db=getDb();const [existing]=await db.select().from(adminAssignments).where(eq(adminAssignments.userId,input.userId)).limit(1);if(existing?.role==="super_admin"&&existing.status==="active"&&(input.role!=="super_admin"||input.status!=="active")){const [total]=await db.select({value:count()}).from(adminAssignments).where(and(eq(adminAssignments.role,"super_admin"),eq(adminAssignments.status,"active")));if(total.value<=1)throw new ApiError(409,"The final super administrator cannot be removed")}await db.insert(adminAssignments).values({userId:input.userId,role:input.role,status:input.status,grantedBy:admin.user.id}).onConflictDoUpdate({target:adminAssignments.userId,set:{role:input.role,status:input.status,grantedBy:admin.user.id,updatedAt:new Date()}});await audit(admin.user.id,"admin.assignment_changed","user",input.userId,{}, {permission:"admins.manage",reason:input.reason,severity:"high",before:existing??{},after:{role:input.role,status:input.status}});return NextResponse.json({success:true})}catch(error){return apiError(error)}}
