import { createHash } from "node:crypto";
import { eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { getDb } from "@/db";
import { contentSnapshots, moderationEvents, reports } from "@/db/schema";
import { requirePermission } from "@/lib/admin";
import { ApiError, apiError } from "@/lib/api";
import { audit } from "@/lib/audit";
import { getModerationTarget, moderationTargetTypes } from "@/lib/moderation-targets";

const schema = z.object({ action: z.enum(["assign", "investigate", "resolve", "dismiss", "snapshot", "legal_hold"]), note: z.string().trim().min(5).max(2000), resolution: z.string().trim().max(1000).optional() });
export async function POST(request: Request, { params }: { params: Promise<{ reportId: string }> }) { try { const admin = await requirePermission("reports.manage"); const { reportId } = await params; const input = schema.parse(await request.json()); const db = getDb(); const [report] = await db.select().from(reports).where(eq(reports.id, reportId)).limit(1); if (!report) throw new ApiError(404, "Report not found"); if (["resolve", "dismiss"].includes(input.action) && !["open", "investigating"].includes(report.status)) throw new ApiError(409, "This report has already been closed"); if (input.action === "assign" || input.action === "investigate") await db.update(reports).set({ assignedTo: admin.user.id, status: "investigating" }).where(eq(reports.id, reportId)); if (["resolve", "dismiss"].includes(input.action)) await db.update(reports).set({ assignedTo: admin.user.id, status: input.action === "resolve" ? "resolved" : "dismissed", resolution: input.resolution ?? input.note, resolvedAt: new Date() }).where(eq(reports.id, reportId)); if (["snapshot", "legal_hold"].includes(input.action)) { if (!moderationTargetTypes.includes(report.targetType as typeof moderationTargetTypes[number])) throw new ApiError(400, "This report target cannot be preserved"); const content = await getModerationTarget(report.targetType as typeof moderationTargetTypes[number], report.targetId); if (!content) throw new ApiError(410, "The reported content is no longer available to preserve"); const serialized = JSON.stringify(content); await db.insert(contentSnapshots).values({ reportId, targetType: report.targetType, targetId: report.targetId, content, contentHash: createHash("sha256").update(serialized).digest("hex"), legalHold: input.action === "legal_hold", capturedBy: admin.user.id }); } await db.insert(moderationEvents).values({ reportId, actorId: admin.user.id, type: input.action, note: input.note, metadata: { resolution: input.resolution } }); await audit(admin.user.id, `admin.report_${input.action}`, "report", reportId, {}, { permission: "reports.manage", reason: input.note, severity: report.priority }); return NextResponse.json({ success: true }); } catch (error) { return apiError(error); } }
