import { NextResponse } from "next/server";
import { and,eq } from "drizzle-orm";
import { z } from "zod";
import { getDb } from "@/db";
import { projectMembers,projects,projectUpdates } from "@/db/schema";
import { ApiError,apiError,requireMember } from "@/lib/api";
import { audit } from "@/lib/audit";
async function access(userId:string,updateId:string){const [row]=await getDb().select({update:projectUpdates,ownerId:projects.ownerId,role:projectMembers.membershipRole}).from(projectUpdates).innerJoin(projects,eq(projects.id,projectUpdates.projectId)).leftJoin(projectMembers,and(eq(projectMembers.projectId,projects.id),eq(projectMembers.userId,userId))).where(eq(projectUpdates.id,updateId)).limit(1);if(!row)throw new ApiError(404,"Update not found");const owner=row.ownerId===userId||row.role==="co_owner";if(row.update.authorId!==userId&&!owner)throw new ApiError(403,"You cannot change this update");return row}
export async function PATCH(request:Request,{params}:{params:Promise<{updateId:string}>}){try{const member=await requireMember(),{updateId}=await params,row=await access(member.id,updateId),input=z.object({body:z.string().trim().min(2).max(3000),type:z.enum(["update","progress","decision","risk","win"]).optional(),milestoneId:z.uuid().nullable().optional()}).parse(await request.json());const [updated]=await getDb().update(projectUpdates).set({...input,updatedAt:new Date()}).where(eq(projectUpdates.id,updateId)).returning();await audit(member.id,"project.update_edited","project_update",updateId,{projectId:row.update.projectId});return NextResponse.json(updated)}catch(error){return apiError(error)}}
export async function DELETE(_:Request,{params}:{params:Promise<{updateId:string}>}){try{const member=await requireMember(),{updateId}=await params,row=await access(member.id,updateId);await getDb().update(projectUpdates).set({status:"deleted",deletedAt:new Date(),updatedAt:new Date()}).where(eq(projectUpdates.id,updateId));await audit(member.id,"project.update_deleted","project_update",updateId,{projectId:row.update.projectId});return NextResponse.json({success:true})}catch(error){return apiError(error)}}
