import { and, eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { getDb } from "@/db";
import { applications, projectMembers, projectRoles, projects, users } from "@/db/schema";
import { ApiError, apiError, requireMember } from "@/lib/api";
import { audit } from "@/lib/audit";
import { createNotification } from "@/lib/notifications";
import { trackProductEvent } from "@/lib/analytics";
import { requireProjectView } from "@/lib/content-access";
const schema=z.object({roleId:z.uuid(),message:z.string().trim().max(1200).optional()});
const normalise=(value:string)=>value.trim().toLowerCase().replace(/[^a-z0-9]+/g," ");
const includesMatch=(candidate:string,requirement:string)=>{const a=normalise(candidate),b=normalise(requirement);return Boolean(a&&b&&(a===b||a.includes(b)||b.includes(a)))};

export async function GET(request:Request,{params}:{params:Promise<{projectId:string}>}){try{const member=await requireMember(),{projectId}=await params,roleId=z.uuid().parse(new URL(request.url).searchParams.get("roleId")),db=getDb();await requireProjectView(member.id,projectId);const [[role],[profile],[membership],[existing]]=await Promise.all([
  db.select({id:projectRoles.id,projectId:projectRoles.projectId,title:projectRoles.title,department:projectRoles.department,description:projectRoles.description,status:projectRoles.status,capacity:projectRoles.capacity,filled:projectRoles.filled,professions:projectRoles.professions,requiredSkills:projectRoles.requiredSkills,usefulSkills:projectRoles.usefulSkills}).from(projectRoles).where(and(eq(projectRoles.id,roleId),eq(projectRoles.projectId,projectId))).limit(1),
  db.select({profession:users.profession,primarySkill:users.primarySkill,secondarySkill:users.secondarySkill,tertiarySkill:users.tertiarySkill,skills:users.skills}).from(users).where(eq(users.id,member.id)).limit(1),
  db.select({userId:projectMembers.userId}).from(projectMembers).where(and(eq(projectMembers.projectId,projectId),eq(projectMembers.userId,member.id))).limit(1),
  db.select({status:applications.status}).from(applications).where(and(eq(applications.roleId,roleId),eq(applications.applicantId,member.id))).limit(1),
]);if(!role||role.status!=="open"||role.filled>=role.capacity)throw new ApiError(404,"This role is no longer open");const skills=[profile?.primarySkill,profile?.secondarySkill,profile?.tertiarySkill,...(profile?.skills??[])].filter((value):value is string=>Boolean(value)),professionMatch=Boolean(profile?.profession&&role.professions.some(value=>includesMatch(profile.profession!,value))),requiredMatches=role.requiredSkills.filter(required=>skills.some(skill=>includesMatch(skill,required))),usefulMatches=role.usefulSkills.filter(required=>skills.some(skill=>includesMatch(skill,required))),hasRequirements=role.professions.length+role.requiredSkills.length+role.usefulSkills.length>0,match=!hasRequirements||professionMatch||requiredMatches.length>0||usefulMatches.length>0;return NextResponse.json({role,fit:{match,profession:profile?.profession??null,professionMatch,skills,requiredMatches,usefulMatches,warning:match?null:"Your current profession and career skills do not closely match this role. You can still apply if your experience is relevant—explain it clearly to the owner."},alreadyMember:Boolean(membership),existingStatus:existing?.status??null})}catch(error){return apiError(error)}}

export async function POST(request:Request,{params}:{params:Promise<{projectId:string}>}){try{const member=await requireMember(),{projectId}=await params,input=schema.parse(await request.json()),db=getDb();await requireProjectView(member.id,projectId);const [role]=await db.select({role:projectRoles,ownerId:projects.ownerId,projectTitle:projects.title}).from(projectRoles).innerJoin(projects,eq(projects.id,projectRoles.projectId)).where(eq(projectRoles.id,input.roleId)).limit(1);if(!role||role.role.projectId!==projectId||role.role.status!=="open"||role.role.filled>=role.role.capacity)throw new ApiError(404,"This role is no longer open");if(role.ownerId===member.id)throw new ApiError(409,"You already own this project");const [[membership],[existing]]=await Promise.all([db.select({id:projectMembers.userId}).from(projectMembers).where(and(eq(projectMembers.projectId,projectId),eq(projectMembers.userId,member.id))).limit(1),db.select({status:applications.status}).from(applications).where(and(eq(applications.roleId,input.roleId),eq(applications.applicantId,member.id))).limit(1)]);if(membership)throw new ApiError(409,"You are already part of this project");if(existing)throw new ApiError(409,existing.status==="pending"?"You have already applied for this role":`Your previous application is ${existing.status}`);const [application]=await db.insert(applications).values({projectId,roleId:input.roleId,applicantId:member.id,message:input.message}).returning();await createNotification({userId:role.ownerId,actorId:member.id,type:"application",title:`New application from ${member.name??"an n2 member"}`,body:`${role.role.title} · ${role.projectTitle}`,entityType:"application",entityId:application.id,href:`/?view=projects&project=${projectId}`});await audit(member.id,"project.applied","project",projectId,{applicationId:application.id,roleId:input.roleId});await trackProductEvent({actorId:member.id,event:"project_application",entityType:"project",entityId:projectId});return NextResponse.json(application,{status:201})}catch(error){return apiError(error)}}
